[listener]
type="socket"

[service.httpProxy]
type="http-proxy"
director="lxc"

[[port]]
port="tcp/8080"
services=["httpProxy"]

[director.lxc]
type="lxc"
<...>

[service.ftp]
type="ftp"

[[port]]
port="tcp/21"
services=["ftp"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[service.eos01]
type="eos"

[[port]]
port="tcp/8888"
services=["eos01"]

[service.elastico]
type="elasticsearch"
name="AW2LChf"
cluster_name="elasticsearch"
cluster_uuid="ay20oRi4SHmlOPAyTrPh6A"

[[port]]
port="tcp/9200"
services=["elastico"]

[service.echo01]
type="echo"

[[port]]
port="udp/5555"
services=["echo01"]

[service.dns01]
type="dns"

[[port]]
port="udp/53"
services=["dns01"]

[service.dnsproxy01]
type="dns-proxy"
director="googledns01"

[[port]]
port="udp/53"
services=["dnsproxy01"]

[director.googledns01]
type="forward"
host="8.8.8.8"

[service.cwmp01]
type="cwmp"

[[port]]
port="tcp/3890"
services=["cwmp01"]

[service.counterstrike01]
type="counterstrike"

[[port]]
port="udp/27016"
services=["counterstrike01"]

[service.adb01]
type="adb"

[[port]]
port="tcp/5037"
services=["adb01"]

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022", "tcp/8023"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
image="/data/screenshot-20171030174349.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["telnet"]

[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[[logging]]
output = "stdout"
level = "debug"
