[listener]
type="socket"

[service.sshsimulator]
type="ssh-simulator"

[[port]]
port="tcp/8022"
services=["sshsimulator"]

[service.https]
type="https"

[[port]]
port="tcp/8080"
services=["https"]

[service.vnc]
type="vnc"
image="/data/images/desktop.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["vnc"]

[service.tftp]
type="tftp"

[[port]]
port="udp/69"
services=["tftp"]

[service.redis]
type="redis"
version="4.0.2"
os="Linux 2.6.32-431.el6.x86_64 x86_64"

[[port]]
port="tcp/6379"
services=["redis"]

[service.memcached01]
type="memcached"

[[port]]
port="udp/11211"
services=["memcached01"]

[service.ldap]
type="ldap"
credentials=["admin:admin", "root:root"]
naming-contexts=[ "dc=example,dc=com", "dc=ad,dc=myserver,dc=com" ]
vendor-name=[ "HT Directory Server" ]
vendor-version=[ "0.1.0.0" ]
description=[ "Directory Server" ]
objectclass=[ "dcObject", "organization" ]

[[port]]
port="tcp/389"
services=["ldap"]

[service.ipp]
type="ipp"
server="HP LaserJet"
storage-dir="/tmp/"

[[port]]
port="tcp/631"
services=["ipp"]

[service.ftp]
type="ftp"

[[port]]
port="tcp/21"
services=["ftp"]

[service.ethereum]
type="ethereum"

[[port]]
port="tcp/8545"
services=["ethereum"]

[service.eos01]
type="eos"

[[port]]
port="tcp/8888"
services=["eos01"]

[service.elastico]
type="elasticsearch"
name="AW2LChf"
cluster_name="elasticsearch"
cluster_uuid="ay20oRi4SHmlOPAyTrPh6A"

[[port]]
port="tcp/9200"
services=["elastico"]

[service.echo01]
type="echo"

[[port]]
port="udp/5555"
services=["echo01"]

[service.dns01]
type="dns"

[[port]]
port="udp/53"
services=["dns01"]

[service.cwmp01]
type="cwmp"

[[port]]
port="tcp/3890"
services=["cwmp01"]

[service.counterstrike01]
type="counterstrike"

[[port]]
port="udp/27016"
services=["counterstrike01"]

[service.adb01]
type="adb"

[[port]]
port="tcp/5037"
services=["adb01"]

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
ports=["tcp/8022", "tcp/8023"]
services=["ssh-simulator"]

[service.telnet]
type="telnet"
image="/data/screenshot-20171030174349.png"
server-name="WS-3244"

[[port]]
port="tcp/5900"
services=["telnet"]

[service.smtp]
type="smtp"

[[port]]
port="tcp/25"
services=["smtp"]

[channel.console]
type="console"

[[filter]]
channel=["console"]

[[logging]]
output = "stdout"
level = "debug"
